### PR TITLE
Sanjay Krishna first sprint

### PR DESCRIPTION
**Pull request by sanjaykmenon**

### CODE REVIEW

**Comment by llpk79** [comment]
Hey Sanjay! Great start!
See what happens when you try these `x` and `y` in your plot.
`y = [1,1,2,3,5,8,13,21,34,55]`
`x = len(y)`

**Comment by sanjaykmenon** [comment]
> 
> 
> Hey Sanjay! Great start!
> See what happens when you try these `x` and `y` in your plot.
> `y = [1,1,2,3,5,8,13,21,34,55]`
> `x = len(y)`

okay, i've been breaking my head and seeing that the plot code doesn't run because both are of different dimensions. i tried changing them to a np.array but it doesn't work. so what should i do?

**Comment by sanjaykmenon** [comment]
Okay, i fixed it! Yay! But i'm not sure if this commit thing worked. still figuring that out.

**Comment by llpk79** [comment]
Your commit is right there! You're doing great!

**Comment by llpk79** [comment]
Lambda School Data Science - Making Data-backed Assertions

Good use of pairplot!
Also well done binning columns. Are there any that should be left unbinned? Why?

Try making a crosstab with all features binned.
Assign it to a variable and make some plots with it!!

Good reasoning and arguments for your answers to the posted questions. Can't argue with you :)

**Comment by sanjaykmenon** [comment]
Still need to complete the lending club assignment. I'm not able to complete it today.

Will have it ready over the weekend.

**Comment by llpk79** [comment]
Did your index remain set as the `Date/Time`?

Is your `Date/Time` column of type `Datetime`?

What column has `snow`? `Date/Time` or `Weather`?

**Comment by llpk79** [comment]
Sprint challenge code review:

Part 1 - Load and validate the data

- Load the data as a pandas data frame.
    - Complete.
- Validate that it has the appropriate number of observations (you can check the raw file, and also read the dataset description from UCI).
    - Complete.
- Validate that you have no missing values.
    - Complete.
- Add informative names to the features.
    - Well done.
- The survival variable is encoded as 1 for surviving >5 years and 2 for not - change this to be 0 for not surviving and 1 for surviving >5 years (0/1 is a more traditional encoding of binary variables)
    - Interesting way of doing this. I like it.
- At the end, print the first five rows of the dataset to demonstrate the above.
    - Complete.
- Bonus: make `year_of_operation` type datetime.
    - ✔️

Part 2 - Examine the distribution and relationships of the features

- Explore the data - create at least 2 tables (can be summary statistics or crosstabulations) and 2 plots illustrating the nature of the data.
    - Good job exploring several cross-tabs. What do you see here?
    - Check out `pd.qcut()`
    - Make sure to `import matplotlib...` before calling `.plt`

Part 3 - DataFrame Filtering

- Use DataFrame filtering to subset the data into two smaller dataframes. You should make one dataframe for individuals who survived >5 years and a second dataframe for individuals who did not.
    - Complete.
- Create a graph with each of the dataframes (can be the same graph type) to show the differences in Age and Number of Positive Axillary Nodes Detected between the two groups.
    - Complete.

Part 4 - Analysis and Interpretation

- What is at least one feature that looks to have a positive relationship with survival? (As that feature goes up in value rate of survival increases)
    - Age, or year_of_operation?
- What is at least one feature that looks to have a negative relationship with survival? (As that feature goes down in value rate of survival increases)
    - 👍 
- How are those two features related with each other, and what might that mean?
    - Give this one some more thought. What do you mean by the dataset not being balanced?

**Pull request closed without merging**
